FROM node:20-alpine3.16

# Create app directory
WORKDIR /app_front
ADD . /app_front
# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
RUN npm cache clean --force
RUN npm install
# If you are building your code for production

# Bundle app source
COPY . .

EXPOSE 3000
CMD [ "npm", "run", "dev" ]